name: Run

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.6

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          uv sync --frozen --no-install-project --no-dev --python-preference=only-system

      - name: Run Program
        run: |
          networks=$(paste -sd, networks.txt)
          uv run python main.py --search "$networks"

      - name: Prettify files
        run: |
          npx prettier --write .

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -z $(git status --porcelain) ]]; then
              echo "changes=false" >> $GITHUB_OUTPUT
          else
              echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit files
        if: ${{ steps.check_changes.outputs.changes == 'true' && github.ref == 'refs/heads/main' }}
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Add changes"

      - name: Push changes
        if: ${{ steps.check_changes.outputs.changes == 'true' && github.ref == 'refs/heads/main' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
